"""custom sections and theme

Revision ID: aed417b663bd
Revises: 145681c32385
Create Date: 2026-09-27 17:35:39.266994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aed417b663bd"
down_revision: str | Sequence[str] | None = "145681c32385"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


CUSTOM_SECTION_TYPES = ("story", "gallery", "text", "cta")
BUILT_IN_ONLY = (
    "section_type IN ('booking', 'event_types', 'faq', 'flavors', 'hero', "
    "'how_it_works', 'packages_menu')"
)


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate doesn't see new enum values. Adding them is safe inside the migration's
    # transaction because nothing below uses them yet.
    for section_type in CUSTOM_SECTION_TYPES:
        op.execute(f"ALTER TYPE section_type ADD VALUE IF NOT EXISTS '{section_type}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_theme",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("colors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("heading_font", sa.String(length=60), nullable=False),
        sa.Column("body_font", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_theme")),
    )
    op.drop_constraint(op.f("uq_page_sections_page"), "page_sections", type_="unique")
    op.create_index(
        "ix_page_sections_page_position", "page_sections", ["page", "position"], unique=False
    )
    op.create_index(
        "uq_page_sections_page_built_in",
        "page_sections",
        ["page", "section_type"],
        unique=True,
        postgresql_where=sa.text(BUILT_IN_ONLY),
    )
    # ### end Alembic commands ###
    # Keep Supabase's Data API out of the new table (see "enable row level security").
    op.execute("ALTER TABLE site_theme ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # Custom sections can repeat, which the old unique constraint forbids: remove them first.
    # (Postgres can't drop enum values; the extra section_type values stay, unused.)
    custom_types = ", ".join(f"'{section_type}'" for section_type in CUSTOM_SECTION_TYPES)
    op.execute(f"DELETE FROM page_sections WHERE section_type::text IN ({custom_types})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_page_sections_page_built_in",
        table_name="page_sections",
        postgresql_where=sa.text(BUILT_IN_ONLY),
    )
    op.drop_index("ix_page_sections_page_position", table_name="page_sections")
    op.create_unique_constraint(
        op.f("uq_page_sections_page"),
        "page_sections",
        ["page", "section_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("site_theme")
    # ### end Alembic commands ###
