"""create site content

Revision ID: 1867d8c1dd99
Revises: 4d1e72e8573b
Create Date: 2026-09-27 16:03:04.338889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1867d8c1dd99"
down_revision: str | Sequence[str] | None = "4d1e72e8573b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page", sa.String(length=40), nullable=False),
        sa.Column(
            "section_type",
            sa.Enum(
                "hero",
                "event_types",
                "packages_menu",
                "how_it_works",
                "flavors",
                "faq",
                "booking",
                name="section_type",
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_sections")),
        sa.UniqueConstraint("page", "section_type", name=op.f("uq_page_sections_page")),
    )
    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_name", sa.String(length=80), nullable=False),
        sa.Column("tagline", sa.String(length=160), nullable=False),
        sa.Column("phone_display", sa.String(length=30), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("instagram_handle", sa.String(length=60), nullable=True),
        sa.Column("instagram_url", sa.String(length=500), nullable=True),
        sa.Column("service_area", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_settings")
    op.drop_table("page_sections")
    # ### end Alembic commands ###
    # drop_table doesn't remove Postgres enum types created alongside the table.
    sa.Enum(name="section_type").drop(op.get_bind(), checkfirst=True)
