"""create packages and bookings

Revision ID: 48707b0be226
Revises:
Create Date: 2026-09-27 15:11:55.423798

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48707b0be226"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("duration_hours", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("duration_hours > 0", name=op.f("ck_packages_duration_hours_positive")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_packages_price_not_negative")),
        sa.CheckConstraint("servings > 0", name=op.f("ck_packages_servings_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("slug", name=op.f("uq_packages_slug")),
    )
    op.create_index(
        "ix_packages_is_active_position", "packages", ["is_active", "position"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=12), nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("package_name", sa.String(length=120), nullable=False),
        sa.Column("package_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_start_time", sa.Time(), nullable=False),
        sa.Column("venue_address", sa.String(length=500), nullable=False),
        sa.Column("guest_count", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("customer_phone", sa.String(length=30), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "approved", "declined", "completed", "cancelled", name="booking_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column(
            "status_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("guest_count > 0", name=op.f("ck_bookings_guest_count_positive")),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_bookings_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("reference", name=op.f("uq_bookings_reference")),
    )
    op.create_index(op.f("ix_bookings_event_date"), "bookings", ["event_date"], unique=False)
    op.create_index(op.f("ix_bookings_package_id"), "bookings", ["package_id"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_package_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_event_date"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_packages_is_active_position", table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
    # drop_table doesn't remove Postgres enum types created alongside the table.
    sa.Enum(name="booking_status").drop(op.get_bind(), checkfirst=True)
