"""proposals and email log

Revision ID: 0cd5e1df31d6
Revises: aed417b663bd
Create Date: 2026-09-27 20:24:15.206033

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cd5e1df31d6"
down_revision: str | Sequence[str] | None = "aed417b663bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


NEW_TABLES = ("proposals", "proposal_items", "email_log")
NEW_ENUMS = ("proposal_status", "email_template", "email_status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("public_token", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "sent", "accepted", "declined", name="proposal_status"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("discount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deposit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decline_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("deposit >= 0", name=op.f("ck_proposals_deposit_not_negative")),
        sa.CheckConstraint("discount >= 0", name=op.f("ck_proposals_discount_not_negative")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_proposals_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
        sa.UniqueConstraint("public_token", name=op.f("uq_proposals_public_token")),
    )
    op.create_index(op.f("ix_proposals_booking_id"), "proposals", ["booking_id"], unique=False)
    op.create_table(
        "email_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=True),
        sa.Column("proposal_id", sa.Integer(), nullable=True),
        sa.Column(
            "template",
            sa.Enum(
                "booking_received",
                "booking_approved",
                "booking_declined",
                "proposal_sent",
                "proposal_response",
                name="email_template",
            ),
            nullable=False,
        ),
        sa.Column("to_address", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column(
            "status", sa.Enum("sent", "failed", "skipped", name="email_status"), nullable=False
        ),
        sa.Column("provider_message_id", sa.String(length=100), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_email_log_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_email_log_proposal_id_proposals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_log")),
    )
    op.create_index(op.f("ix_email_log_booking_id"), "email_log", ["booking_id"], unique=False)
    op.create_index(op.f("ix_email_log_proposal_id"), "email_log", ["proposal_id"], unique=False)
    op.create_table(
        "proposal_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_proposal_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_proposal_items_unit_price_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_proposal_items_proposal_id_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_items")),
    )
    op.create_index(
        op.f("ix_proposal_items_proposal_id"), "proposal_items", ["proposal_id"], unique=False
    )
    # ### end Alembic commands ###
    # Keep Supabase's Data API out of the new tables (see "enable row level security").
    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposal_items_proposal_id"), table_name="proposal_items")
    op.drop_table("proposal_items")
    op.drop_index(op.f("ix_email_log_proposal_id"), table_name="email_log")
    op.drop_index(op.f("ix_email_log_booking_id"), table_name="email_log")
    op.drop_table("email_log")
    op.drop_index(op.f("ix_proposals_booking_id"), table_name="proposals")
    op.drop_table("proposals")
    # ### end Alembic commands ###
    # drop_table doesn't remove Postgres enum types created alongside the tables.
    for enum_name in NEW_ENUMS:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
