# Keep in sync with the frontend booking form limits.

BOOKING_REFERENCE_MAX_LENGTH = 12
MIN_BOOKING_LEAD_DAYS = 1
MAX_BOOKING_ADVANCE_DAYS = 365
MIN_GUEST_COUNT = 1
MAX_GUEST_COUNT = 1000
MIN_ADDRESS_LENGTH = 5
MAX_ADDRESS_LENGTH = 500
MAX_CUSTOMER_NAME_LENGTH = 120
MAX_PHONE_LENGTH = 30
MAX_NOTES_LENGTH = 1000
MAX_HONEYPOT_LENGTH = 200
MAX_ADMIN_NOTES_LENGTH = 2000
MAX_SEARCH_LENGTH = 100
