# Column sizes and business limits shared by models, schemas and services.
# Keep in sync with frontend/src/features/bookings/constants.ts.

MONEY_PRECISION = 12
MONEY_SCALE = 2

URL_MAX_LENGTH = 500

PACKAGE_NAME_MAX_LENGTH = 120
PACKAGE_SLUG_MAX_LENGTH = 140

BOOKING_REFERENCE_MAX_LENGTH = 12
MIN_BOOKING_LEAD_DAYS = 1
MAX_BOOKING_ADVANCE_DAYS = 365
MIN_GUEST_COUNT = 1
MAX_GUEST_COUNT = 1000
MIN_ADDRESS_LENGTH = 5
MAX_ADDRESS_LENGTH = 500
MAX_CUSTOMER_NAME_LENGTH = 120
MAX_PHONE_LENGTH = 30
MAX_EMAIL_LENGTH = 255
MAX_NOTES_LENGTH = 1000
MAX_HONEYPOT_LENGTH = 200
